Leave Management System/force-app/main/default/objects/Leave__c/Leave__c.object-meta.xml
<CustomObject>
    <description>It contains the records of leaves the Users has taken.</description>
    <label>Leave</label>
    <nameField>
        <displayFormat>LVE-{0000}</displayFormat>
        <label>Leave Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leaves</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Leave Management System/force-app/main/default/objects/Leave__c/fields/Days_Taken__c.field-meta.xml
<CustomField>
    <fullName>Days_Taken__c</fullName>
    <formula>IF(
    OR(
        TEXT(Status__c) = &quot;Approved&quot;,
        TEXT(Status__c) = &quot;Active&quot;,
        TEXT(Status__c) = &quot;Inactive&quot;
    ),
    (
        5 * FLOOR( ( End_Date__c - DATE(1900, 1, 8) ) / 7 ) +
        MIN( 5, MOD( End_Date__c - DATE(1900, 1, 8), 7 ) )
    )
    -
    (
        5 * FLOOR( ( Start_Date__c - DATE(1900, 1, 8) ) / 7 ) +
        MIN( 5, MOD( Start_Date__c - DATE(1900, 1, 8), 7 ) )
    )
    +
    CASE(
        WEEKDAY(End_Date__c),
        2, 1,
        3, 1,
        4, 1,
        5, 1,
        6, 1,
        0
    ),
    
    0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Taken</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Leave Management System/force-app/main/default/objects/Leave__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Indicated when the leave ends.</description>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

Leave Management System/force-app/main/default/objects/Leave__c/fields/Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>Leave_Type__c</fullName>
    <description>What type of leave it is.</description>
    <label>Leave Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Earned_Leave</fullName>
                <label>Earned Leave</label>
            </value>
            <value>
                <fullName>Sick_Leave</fullName>
                <label>Sick Leave</label>
            </value>
            <value>
                <fullName>Unpaid_Leave</fullName>
                <label>Unpaid Leave</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Leave Management System/force-app/main/default/objects/Leave__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Indicated when the leave is startes</description>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

Leave Management System/force-app/main/default/objects/Leave__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Shows the status of the leave.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <isActive>false</isActive>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Leave Management System/force-app/main/default/classes/CaseTriggerHandler.cls
public with sharing class CaseTriggerHandler {
/********************************************************************************************************************
 *@Author:          CRM Team Innovation
 *@methodName:      reassignCasesForUsersOnLeave
 *@param:         newCases-List of new Case records to check for reassignment
 *@Description:     This method checks if the owners of the newly created Case records are on active leave.
    *                  If they are, it invokes the LeaveTriggerHandler to handle the reassignment logic.
 **********************************************************************************************************************/
public static void reassignCasesForUsersOnLeave(List<Case> newCases) {
    Set<Id> ownerIds = new Set<Id>();
    for (Case c : newCases) {
        ownerIds.add(c.OwnerId);
    }
    if (!ownerIds.isEmpty()) {
        List<Leave__c> leaves = [SELECT 
                                Id,OwnerId,Start_Date__c,End_Date__c,Status__c,Leave_Type__c,
                                Days_Taken__c
                            FROM 
                                Leave__c
                            WHERE 
                                OwnerId IN :ownerIds
                            AND 
                                Status__c = 'Active'];
        Map<Id, Leave__c> oldleaveMapDummy = new Map<Id, Leave__c>();
        for(Leave__c lv : leaves){
            Leave__c oldLeave = lv.clone();
            oldLeave.Status__c = 'Pending';
            oldleaveMapDummy.put(lv.Id, oldLeave);
        }
        if(!leaves.isEmpty()){
            LeaveTriggerHandler.handleAfterUpdate(leaves, oldleaveMapDummy);
        }
        }
    }
}