Leave Management System/force-app/main/default/objects/Leave__c/Leave__c.object-meta.xml
<CustomObject>
    <description>It contains the records of leaves the Users has taken.</description>
    <label>Leave</label>
    <nameField>
        <displayFormat>LVE-{0000}</displayFormat>
        <label>Leave Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leaves</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Leave Management System/force-app/main/default/objects/Leave__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Indicated when the leave is startes</description>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

Leave Management System/force-app/main/default/objects/Leave__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Shows the status of the leave.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <isActive>false</isActive>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Leave Management System/force-app/main/default/classes/LeaveStatusScheduler.cls
public with sharing class LeaveStatusScheduler implements Schedulable {
    public void execute(SchedulableContext sc) {
        try {
            List<Leave__c> leavesToUpdate = [
                SELECT
                    Id, Status__c, Start_Date__c
                FROM
                    Leave__c
                WHERE
                    Start_Date__c <= TODAY
                AND
                    Status__c = 'Approved'
            ];
            if (!leavesToUpdate.isEmpty()) {
                List<Leave__c> leavesToUpdateList = new List<Leave__c>();
                for (Leave__c leave : leavesToUpdate) {
                    leave.Status__c = 'Active';
                    leavesToUpdateList.add(leave);
                }
                if (!leavesToUpdateList.isEmpty()) {
                    Database.update(leavesToUpdateList, false);
                }
            }
        } catch (Exception e) {
            System.debug('Error in LeaveStatusScheduler: ' + e.getMessage());
        }
    }
}